=begin
#ChannelEngine Merchant API

#ChannelEngine API for merchants

The version of the OpenAPI document: 2.9.9

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.1.1

=end

require 'date'
require 'time'

module ChannelEngineMerchantApiClient
  class AdvanceSettingsResponse
    attr_accessor :manage_stock

    attr_accessor :disable_address_validation

    attr_accessor :skip_house_number_validation

    attr_accessor :skip_house_number_validation_for_country_codes

    attr_accessor :set_orders_to_closed_on_import

    attr_accessor :disable_stock_reservation

    attr_accessor :disable_auto_order_cancellation

    attr_accessor :automatically_set_phone_number_if_empty

    attr_accessor :default_vat_rate

    attr_accessor :order_too_long_on_new_hours_offset

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'manage_stock' => :'ManageStock',
        :'disable_address_validation' => :'DisableAddressValidation',
        :'skip_house_number_validation' => :'SkipHouseNumberValidation',
        :'skip_house_number_validation_for_country_codes' => :'SkipHouseNumberValidationForCountryCodes',
        :'set_orders_to_closed_on_import' => :'SetOrdersToClosedOnImport',
        :'disable_stock_reservation' => :'DisableStockReservation',
        :'disable_auto_order_cancellation' => :'DisableAutoOrderCancellation',
        :'automatically_set_phone_number_if_empty' => :'AutomaticallySetPhoneNumberIfEmpty',
        :'default_vat_rate' => :'DefaultVatRate',
        :'order_too_long_on_new_hours_offset' => :'OrderTooLongOnNewHoursOffset'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'manage_stock' => :'Boolean',
        :'disable_address_validation' => :'Boolean',
        :'skip_house_number_validation' => :'Boolean',
        :'skip_house_number_validation_for_country_codes' => :'Array<String>',
        :'set_orders_to_closed_on_import' => :'Boolean',
        :'disable_stock_reservation' => :'Boolean',
        :'disable_auto_order_cancellation' => :'Boolean',
        :'automatically_set_phone_number_if_empty' => :'String',
        :'default_vat_rate' => :'Float',
        :'order_too_long_on_new_hours_offset' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'skip_house_number_validation_for_country_codes',
        :'automatically_set_phone_number_if_empty',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `ChannelEngineMerchantApiClient::AdvanceSettingsResponse` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `ChannelEngineMerchantApiClient::AdvanceSettingsResponse`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'manage_stock')
        self.manage_stock = attributes[:'manage_stock']
      end

      if attributes.key?(:'disable_address_validation')
        self.disable_address_validation = attributes[:'disable_address_validation']
      end

      if attributes.key?(:'skip_house_number_validation')
        self.skip_house_number_validation = attributes[:'skip_house_number_validation']
      end

      if attributes.key?(:'skip_house_number_validation_for_country_codes')
        if (value = attributes[:'skip_house_number_validation_for_country_codes']).is_a?(Array)
          self.skip_house_number_validation_for_country_codes = value
        end
      end

      if attributes.key?(:'set_orders_to_closed_on_import')
        self.set_orders_to_closed_on_import = attributes[:'set_orders_to_closed_on_import']
      end

      if attributes.key?(:'disable_stock_reservation')
        self.disable_stock_reservation = attributes[:'disable_stock_reservation']
      end

      if attributes.key?(:'disable_auto_order_cancellation')
        self.disable_auto_order_cancellation = attributes[:'disable_auto_order_cancellation']
      end

      if attributes.key?(:'automatically_set_phone_number_if_empty')
        self.automatically_set_phone_number_if_empty = attributes[:'automatically_set_phone_number_if_empty']
      end

      if attributes.key?(:'default_vat_rate')
        self.default_vat_rate = attributes[:'default_vat_rate']
      end

      if attributes.key?(:'order_too_long_on_new_hours_offset')
        self.order_too_long_on_new_hours_offset = attributes[:'order_too_long_on_new_hours_offset']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          manage_stock == o.manage_stock &&
          disable_address_validation == o.disable_address_validation &&
          skip_house_number_validation == o.skip_house_number_validation &&
          skip_house_number_validation_for_country_codes == o.skip_house_number_validation_for_country_codes &&
          set_orders_to_closed_on_import == o.set_orders_to_closed_on_import &&
          disable_stock_reservation == o.disable_stock_reservation &&
          disable_auto_order_cancellation == o.disable_auto_order_cancellation &&
          automatically_set_phone_number_if_empty == o.automatically_set_phone_number_if_empty &&
          default_vat_rate == o.default_vat_rate &&
          order_too_long_on_new_hours_offset == o.order_too_long_on_new_hours_offset
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [manage_stock, disable_address_validation, skip_house_number_validation, skip_house_number_validation_for_country_codes, set_orders_to_closed_on_import, disable_stock_reservation, disable_auto_order_cancellation, automatically_set_phone_number_if_empty, default_vat_rate, order_too_long_on_new_hours_offset].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = ChannelEngineMerchantApiClient.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
