=begin
#ChannelEngine Merchant API

#ChannelEngine API for merchants

The version of the OpenAPI document: 2.9.3

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.0-SNAPSHOT

=end

require 'date'

module ChannelEngineMerchantApiClient
  class FulfillmentType
    ALL = "ALL".freeze
    ONLY_MERCHANT = "ONLY_MERCHANT".freeze
    ONLY_CHANNEL = "ONLY_CHANNEL".freeze
    MIXED = "MIXED".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = FulfillmentType.constants.select { |c| FulfillmentType::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #FulfillmentType" if constantValues.empty?
      value
    end
  end
end
