=begin
#ChannelEngine API V2

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 2.4.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for ChannelEngineApiClient::CancellationApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CancellationApi' do
  before do
    # run before each test
    @instance = ChannelEngineApiClient::CancellationApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CancellationApi' do
    it 'should create an instance of CancellationApi' do
      expect(@instance).to be_instance_of(ChannelEngineApiClient::CancellationApi)
    end
  end

  # unit tests for cancellation_create
  # Merchant: Create Cancellation
  # For merchants.    Mark (part of) an order as cancelled.
  # @param cancellation 
  # @param [Hash] opts the optional parameters
  # @return [ApiResponse]
  describe 'cancellation_create test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for cancellation_index
  # Channel: Get Cancellations
  # For channels.    Gets all cancellations created since the supplied date.
  # @param created_since 
  # @param [Hash] opts the optional parameters
  # @return [CollectionOfChannelCancellationResponse]
  describe 'cancellation_index test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
