=begin
#ChannelEngine API V2

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 2.4.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for ChannelEngineApiClient::ClientApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ClientApi' do
  before do
    # run before each test
    @instance = ChannelEngineApiClient::ClientApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ClientApi' do
    it 'should create an instance of ClientApi' do
      expect(@instance).to be_instance_of(ChannelEngineApiClient::ClientApi)
    end
  end

  # unit tests for client_get
  # Get API Client
  # This call generates a Swagger API client and returns it as a ZIP
  # @param language The programming language
  # @param [Hash] opts the optional parameters
  # @return [File]
  describe 'client_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
