=begin
#ChannelEngine API V2

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 2.4.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for ChannelEngineApiClient::OfferApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'OfferApi' do
  before do
    # run before each test
    @instance = ChannelEngineApiClient::OfferApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of OfferApi' do
    it 'should create an instance of OfferApi' do
      expect(@instance).to be_instance_of(ChannelEngineApiClient::OfferApi)
    end
  end

  # unit tests for offer_stock_price_update
  # Update stock or price.
  # 
  # @param updates References to the products that should be updated, and the new values  for the stock or price fields. It is possible to supply only one of the two fields  or both.
  # @param [Hash] opts the optional parameters
  # @return [SingleOfCollectionsDictionary2Generic]
  describe 'offer_stock_price_update test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
