=begin
#ChannelEngine API V2

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 2.4.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for ChannelEngineApiClient::OrderFilter
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'OrderFilter' do
  before do
    # run before each test
    @instance = ChannelEngineApiClient::OrderFilter.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of OrderFilter' do
    it 'should create an instance of OrderFilter' do
      expect(@instance).to be_instance_of(ChannelEngineApiClient::OrderFilter)
    end
  end
  describe 'test attribute "statuses"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
       #validator = Petstore::EnumTest::EnumAttributeValidator.new('Array<String>', ["IN_PROGRESS", "SHIPPED", "IN_BACKORDER", "CANCELED", "MANCO", "IN_COMBI", "CLOSED", "NEW", "RETURNED", "REQUIRES_CORRECTION"])
       #validator.allowable_values.each do |value|
       #  expect { @instance.statuses = value }.not_to raise_error
       #end
    end
  end

  describe 'test attribute "merchant_order_nos"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "exclude_marketplace_fulfilled_orders_and_lines"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "fulfillment_type"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
       #validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["ALL", "ONLY_MERCHANT", "ONLY_CHANNEL", "MIXED"])
       #validator.allowable_values.each do |value|
       #  expect { @instance.fulfillment_type = value }.not_to raise_error
       #end
    end
  end

  describe 'test attribute "page"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

