=begin
#ChannelEngine Merchant API

#ChannelEngine API for merchants

OpenAPI spec version: 2.5.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.0-SNAPSHOT

=end

# Common files
require 'channelengine_merchant_api_client_ruby/api_client'
require 'channelengine_merchant_api_client_ruby/api_error'
require 'channelengine_merchant_api_client_ruby/version'
require 'channelengine_merchant_api_client_ruby/configuration'

# Models
require 'channelengine_merchant_api_client_ruby/models/address'
require 'channelengine_merchant_api_client_ruby/models/api_response'
require 'channelengine_merchant_api_client_ruby/models/collection_of_merchant_order_response'
require 'channelengine_merchant_api_client_ruby/models/collection_of_merchant_return_response'
require 'channelengine_merchant_api_client_ruby/models/extra_data_item'
require 'channelengine_merchant_api_client_ruby/models/merchant_cancellation_line_request'
require 'channelengine_merchant_api_client_ruby/models/merchant_cancellation_request'
require 'channelengine_merchant_api_client_ruby/models/merchant_order_line_response'
require 'channelengine_merchant_api_client_ruby/models/merchant_order_response'
require 'channelengine_merchant_api_client_ruby/models/merchant_product_request'
require 'channelengine_merchant_api_client_ruby/models/merchant_product_response'
require 'channelengine_merchant_api_client_ruby/models/merchant_return_line_request'
require 'channelengine_merchant_api_client_ruby/models/merchant_return_line_response'
require 'channelengine_merchant_api_client_ruby/models/merchant_return_request'
require 'channelengine_merchant_api_client_ruby/models/merchant_return_response'
require 'channelengine_merchant_api_client_ruby/models/merchant_shipment_line_request'
require 'channelengine_merchant_api_client_ruby/models/merchant_shipment_request'
require 'channelengine_merchant_api_client_ruby/models/merchant_shipment_tracking_request'
require 'channelengine_merchant_api_client_ruby/models/merchant_stock_price_update_request'
require 'channelengine_merchant_api_client_ruby/models/order_acknowledgement'
require 'channelengine_merchant_api_client_ruby/models/order_filter'
require 'channelengine_merchant_api_client_ruby/models/product_creation_result'
require 'channelengine_merchant_api_client_ruby/models/product_message'
require 'channelengine_merchant_api_client_ruby/models/single_of_collections_dictionary2_generic'
require 'channelengine_merchant_api_client_ruby/models/single_of_merchant_product_response'
require 'channelengine_merchant_api_client_ruby/models/single_of_product_creation_result'

# APIs
require 'channelengine_merchant_api_client_ruby/api/cancellation_api'
require 'channelengine_merchant_api_client_ruby/api/offer_api'
require 'channelengine_merchant_api_client_ruby/api/order_api'
require 'channelengine_merchant_api_client_ruby/api/product_api'
require 'channelengine_merchant_api_client_ruby/api/return_api'
require 'channelengine_merchant_api_client_ruby/api/shipment_api'

module ChannelEngineMerchantApiClient
  class << self
    # Customize default settings for the SDK using block.
    #   ChannelEngineMerchantApiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
