=begin
#ChannelEngine API V2

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 2.4.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0-SNAPSHOT

=end

# Common files
require 'channelengine_api_client_ruby/api_client'
require 'channelengine_api_client_ruby/api_error'
require 'channelengine_api_client_ruby/version'
require 'channelengine_api_client_ruby/configuration'

# Models
require 'channelengine_api_client_ruby/models/api_response'
require 'channelengine_api_client_ruby/models/channel_cancellation_line_response'
require 'channelengine_api_client_ruby/models/channel_cancellation_response'
require 'channelengine_api_client_ruby/models/channel_offer_response'
require 'channelengine_api_client_ruby/models/channel_order_line_request'
require 'channelengine_api_client_ruby/models/channel_order_request'
require 'channelengine_api_client_ruby/models/channel_processed_changes_request'
require 'channelengine_api_client_ruby/models/channel_product_changes_response'
require 'channelengine_api_client_ruby/models/channel_product_response'
require 'channelengine_api_client_ruby/models/channel_references_request'
require 'channelengine_api_client_ruby/models/channel_return_line_request'
require 'channelengine_api_client_ruby/models/channel_return_line_response'
require 'channelengine_api_client_ruby/models/channel_return_request'
require 'channelengine_api_client_ruby/models/channel_return_response'
require 'channelengine_api_client_ruby/models/channel_shipment_line_response'
require 'channelengine_api_client_ruby/models/channel_shipment_response'
require 'channelengine_api_client_ruby/models/collection_of_channel_cancellation_response'
require 'channelengine_api_client_ruby/models/collection_of_channel_offer_response'
require 'channelengine_api_client_ruby/models/collection_of_channel_return_response'
require 'channelengine_api_client_ruby/models/collection_of_channel_shipment_response'
require 'channelengine_api_client_ruby/models/collection_of_merchant_order_response'
require 'channelengine_api_client_ruby/models/collection_of_merchant_return_response'
require 'channelengine_api_client_ruby/models/entities_address_models'
require 'channelengine_api_client_ruby/models/extra_data_item'
require 'channelengine_api_client_ruby/models/merchant_cancellation_line_request'
require 'channelengine_api_client_ruby/models/merchant_cancellation_request'
require 'channelengine_api_client_ruby/models/merchant_order_line_response'
require 'channelengine_api_client_ruby/models/merchant_order_response'
require 'channelengine_api_client_ruby/models/merchant_product_request'
require 'channelengine_api_client_ruby/models/merchant_product_response'
require 'channelengine_api_client_ruby/models/merchant_return_line_request'
require 'channelengine_api_client_ruby/models/merchant_return_line_response'
require 'channelengine_api_client_ruby/models/merchant_return_request'
require 'channelengine_api_client_ruby/models/merchant_return_response'
require 'channelengine_api_client_ruby/models/merchant_shipment_line_request'
require 'channelengine_api_client_ruby/models/merchant_shipment_request'
require 'channelengine_api_client_ruby/models/merchant_shipment_tracking_request'
require 'channelengine_api_client_ruby/models/merchant_stock_price_update_request'
require 'channelengine_api_client_ruby/models/order_acknowledgement'
require 'channelengine_api_client_ruby/models/order_filter'
require 'channelengine_api_client_ruby/models/product_creation_result'
require 'channelengine_api_client_ruby/models/product_message'
require 'channelengine_api_client_ruby/models/single_of_channel_product_changes_response'
require 'channelengine_api_client_ruby/models/single_of_collections_dictionary2_generic'
require 'channelengine_api_client_ruby/models/single_of_merchant_product_response'
require 'channelengine_api_client_ruby/models/single_of_product_creation_result'

# APIs
require 'channelengine_api_client_ruby/api/cancellation_api'
require 'channelengine_api_client_ruby/api/client_api'
require 'channelengine_api_client_ruby/api/offer_api'
require 'channelengine_api_client_ruby/api/order_api'
require 'channelengine_api_client_ruby/api/product_api'
require 'channelengine_api_client_ruby/api/return_api'
require 'channelengine_api_client_ruby/api/shipment_api'

module ChannelEngineApiClient
  class << self
    # Customize default settings for the SDK using block.
    #   ChannelEngineApiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
